person:
  last-name: qinjiang${random.uuid}
  age: ${random.int}
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,k2: v2}
  hello: happy
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hello:Hello}_旺财
    age: 2
    
dog:
  first-name: 阿黄
  age: 3
  
server:
  port: 8081
  
spring:
  profiles:
    active: dev

  messages:
    basename: i18n.login

---
server:
  port: 8082
spring:
  profiles: dev
  
---
server:
  port: 8083
spring:
  profiles: test